### Get all
GET http://localhost:3001/api/persons/

### Get single
GET http://localhost:3001/api/persons/3

### Get single invalid id
GET http://localhost:3001/api/persons/1000

### Post new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Krumbo Bodorp",
    "number": "123-456-7890"
}

### Post new person(missing name)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Krumbo Bodorp"
}

### Post new person(missing number)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "123-456-7890"
}

### Post new person(empty request body)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{

}


### Delete specific person
DELETE http://localhost:3001/api/persons/3

### Delete nonexistent person
DELETE http://localhost:3001/api/persons/1000
